package models

import "gorm.io/gorm"

// User represents a user in the system
// This struct maps directly to the "users" table in the database.
type User struct {
	// ID is the primary key, automatically generated by the database
	ID uint `gorm:"primaryKey" json:"id"`

	// Email must be unique and cannot be empty
	// json:"email" tells Go how to name this field when converting to/from JSON
	Email string `gorm:"unique;not null" json:"email"`

	// Password is stored as a hash, never as plain text
	// json:"-" ensures the password field is NEVER sent back in the JSON response
	Password string `gorm:"not null" json:"-"`

	Name    string `gorm:"not null" json:"name"`
	Tel     string `json:"tel"`
	Age     int    `json:"age"`
	Address string `json:"address"`
	City    string `json:"city"`
	Country string `json:"country"`
	Gender  string `json:"gender"`

	// gorm:"default:false" sets the database column default value to false
	EmailVerified bool `gorm:"default:false" json:"email_verified"`

	// Roles represents a Many-to-Many relationship
	// A user can have multiple roles, and a role can belong to multiple users
	// "many2many:user_roles" tells GORM to create a join table named "user_roles"
	Roles []Role `gorm:"many2many:user_roles;" json:"roles"`

	// Timestamps are automatically managed by GORM
	CreatedAt int64 `gorm:"autoCreateTime:milli" json:"created_at"`
	UpdatedAt int64 `gorm:"autoUpdateTime:milli" json:"updated_at"`

	// DeletedAt provides "Soft Delete" functionality.
	// When we "delete" a user, it just sets this timestamp.
	// The record stays in the DB but GORM ignores it in normal queries.
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
}

// TableName specifies the table name for User
// By default GORM plurals struct names (User -> users), but explicit naming is safe.
func (User) TableName() string {
	return "users"
}

// Role represents a role in the system (e.g. "admin", "user")
type Role struct {
	ID        uint   `gorm:"primaryKey" json:"id"`
	Name      string `gorm:"unique;not null" json:"name"`
	Users     []User `gorm:"many2many:user_roles;" json:"users,omitempty"`
	CreatedAt int64  `gorm:"autoCreateTime:milli" json:"created_at"`
	UpdatedAt int64  `gorm:"autoUpdateTime:milli" json:"updated_at"`
}

// TableName specifies the table name for Role
func (Role) TableName() string {
	return "roles"
}

// HasRole checks if the user has a specific role
// This is a helper method we can call on any User instance.
func (u *User) HasRole(roleName string) bool {
	for _, role := range u.Roles {
		if role.Name == roleName {
			return true
		}
	}
	return false
}
